### ISSUE TITLE
安卓7.0无法注入

### ISSUE THREAD

**Issue by wjy000** [MelonWXD/ELFHooker#1]
5.0,6.0系统都可以正常注入并加载so,但是7.0系统不管是32位还是64位都无法注入,请问这是什么原因呢?
log如下
pid: 12577, process name: test.test.testhider
0x40112c91: module is /system/bin/linker
dlopen: local 0x40112c91, remote 0x401d2c91
0x4053fd51: module is /system/lib/libc.so
mmap: local 0x4053fd51, remote 0x42af0d51
mmap: buffer 0x40127000, length: 57
dlopen: r0 00000000 pc 00000000

**Comment by MelonWXD** [comment]
不好意思，最近有点私事，目前没有余力跟进这个问题，可以试试其他相同思路的hook框架

**Comment by ohyeah521** [comment]
@wjy000  Android 7.x以上要用到这个https://github.com/rrrfff/ndk_dlopen库

**Comment by ohyeah521** [comment]
@wjy000 Android6.0  32位系统

我hook 不到 strcat、strcpy，你可以吗？

**Comment by wjy000** [comment]
> 
> 
> @wjy000 Android6.0 32位系统
> 
> 我hook 不到 strcat、strcpy，你可以吗？

没继续研究这方面了
